language: ruby
rvm:
- 2.1
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./_site/"
  - GH_REF="tomtone/tomtone.github.io"
  - secure: "W7Ei6naYweyn3IBGaOpcoIUBmfE4CAqbmeFCLjdHx0fhRP0UYpWhLpy4xBk0bGJ3d7fwz9OMhIbrBlAsDUZus+XV9QM8Qq0AeaMZQ625bNZMoxjJcl5YKAmar28qVsMJNRbnM83WJLbyW5oWTkO1YANMRLhjtXoDE8A9T8CUBrx/s6EgRmTQnYeAFnQ8ENGdWJ1XrJ92EVXiLXKbN+fEw7k9fqloiovQydIJtz2HASNVaAwxVpESNagn1yReY2yRPI6kFIJv85vW1JouRaeP8UrB1kjhlRTQY3MLkLe/1E33TLaV3pw8R2zT9EUKQCJnTDkDsGIQvr6LOJZhV9IIAtJcoXCh21cpPXdEQSIDKSG9v3o/r3oOrFjpJoZYhJHIheO93XetqJT7ZDbd1jkjHlARV4pwawrNVz5Alf09DUmJhK0OuBdmqTmcsDZN8o29/Og1vwWcX3OcWidAhMEPCrY64y5tKtnzLzbQNbzFhpp5d3qsR4szqNcBMISezP1t0bjoDN0FXj7zh301ohYXzDNfkCGdkzRWZqlVeaYLOyt1sqJgtf09GZqJRR118WxFh8XKWEPRWPNK/W3VyI8tYCvgdMmSW4EcwXHAKfeYDCcXgphObdE4+0YPEOwh4SUPjwqyUCuaCPQSBWt91vCRQBEP86wn917bfCsql9GphbY="
branches:
  only:
  - master
notifications:
  email: false
