sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: x6yYO/ESE/6S3AFGEGuCMrUfVmrR+CpLK4LMooJiH/GnoO0SDEEJxvUXso/bYL9p6syChaRiip3p+FlIGrv/a6rU5gq6agTRcOpexj+fjDVIX8t7LJbNAdbBmKJd7vyDyJWh2PGg28tTSzd6z/68eiP12YqZlwpbEBYM0bg546FTKY84URiJWhIXEXYk5ee4VCHlrfTlZdG8NDRranR2AZ9RYKQsRl/98ezJSVtkHcD+J+/QVTFG6ekS2I4ht8/K89pCpQ+h+Ib+ijRopoq2/g5NB1tTUel7eY8pp2vJVU4xgZ3/BTE+eoQIWvuJ/OJgKGh7/+rVLujqWNPEFsdDVMoKpSSxrcNClyseitrwwjoT7F2MIfo68GWG+dQ+HcWDNQEHG2eP5reSSk6OgCDOVG1D17kL06t7+M7zMtu9r5uJE59FO3GWXc1f+Zwy1B2FzOyw8g9AwVwevcEYevS5zKPqsqoo4pe5B3JoYgrOHR3ei2kto7FUiDMEmb+JWqDLM9EXHH9aDqiNuZffGTPUS27q6IZhDeiI6dtleeogPKfiD7rDg2uu0Xx/965XMNwZEYhvCiwBXIToQxDHMEt8eSyxS6dUFHpT8jDgbNa7sGh4GvZz/zVgsdRZYjg75Xj5vTUiHL5OI83h0os8a/a2f5TbYj0JTh0OBoiKbcCgFxg=
branches:
  only:
  - master
